# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags: -s -w -X github.com/craftamap/bb/cmd.Version={{ .Version }} -X github.com/craftamap/bb/cmd.CommitSHA={{ .Commit }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

brews:
  - goarm: 6
    tap:
      owner: craftamap
      name: homebrew-tap
    commit_author:
      name: "Fabian Siegel"
      email: "fabians1999@gmail.com"
    homepage: "https://siegelfabian.de/"
    description: "inoffical Bitbucket.org command line tool "
    # skip_upload: true

nfpms:
  -
    vendor: craftamap
    maintainer: "Fabian Siegel <fabians1999@gmail.com>"
    description: "inoffical Bitbucket.org command line tool"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
